pages:
  #silex route name = page identifier
  homepage:
    #optional name
    name: homepage
    #optional description
    desc: site main homepage
    #relative url
    url: /home
    #default query parameters values
    default: 
    #HTTP method to use (default = GET)
#    method: GET
    #HTTP status code (default = 200)
#    status: 200
    #document format (default = html) ex : html , xml , css , js, json, xml , atom , rss etc ... 
#    format: html
    #twig template
    template: homepage.html.twig 
    # scalar variables passed to the twig template
    variables:
      app_name: Twig Front Dev
      
  article:
    name: article
    desc: detailed article page
    url: /article/{id}
    default:
      id: 1
    method: GET
    template: article.html.twig 
    variables:
      article: 
        title: fake title
        body: fake body
        
  book:
    name: book
    desc: detailed book page
    url: /book/{id}
    default:
      id: 1
    format: json
    method: GET
    status: 301
    template: book.json.twig 
    variables:
      book: 
        title: fake book title
        body: fake book body

